%\VignetteEngine{knitr}
%\VignetteIndexEntry{R for Proteomics}
%\VignetteKeywords{bioinformatics, proteomics, mass spectrometry}
%\VignettePackage{RforProteomics}

\documentclass[10pt]{article}

\usepackage{hyperref}
\usepackage{breakurl}

\begin{document}
This vignette is a stub. Look at \texttt{vignettes/vigsrc/RforProteomics.Rnw} for the complete Rnw file or on the github repository \url{https://github.com/lgatto/RforProteomics}.

<<session>>=
sessionInfo()
@

\end{document}
